import{NodeIO}from'@gltf-transform/core';import{ALL_EXTENSIONS}from'@gltf-transform/extensions';import{getBounds}from'@gltf-transform/functions';import fs from'node:fs/promises';import assert from'node:assert/strict';import validator from'gltf-validator';
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS),before=await io.read(process.argv[2]),after=await io.read(process.argv[3]),original=new Map(before.getRoot().listNodes().filter(n=>n.getMesh()).map(n=>[n.getName(),n])),repair=JSON.parse(await fs.readFile('review/comfort-blender.json'));let unrelated=0,triangles=0,meshes=0;const quilts=[],trees=[];
for(const n of after.getRoot().listNodes()){if(!n.getMesh())continue;meshes++;const name=n.getName(),old=original.get(name);assert(old||repair.added?.some(x=>x.name===name),name);const b=getBounds(n),a=old?getBounds(old):b;for(const p of n.getMesh().listPrimitives())triangles+=p.getIndices().getCount()/3;
 if(/^fabric 1(?:\.001)?$/.test(name)){const ps=n.getMesh().listPrimitives();assert(ps.every(p=>!p.getMaterial().getBaseColorTexture()&&!p.getMaterial().getOcclusionTexture()));assert.deepEqual(ps[0].getMaterial().getBaseColorFactor().map(v=>+v.toFixed(3)),[.012,.022,.045,1]);const tris=ps.reduce((s,p)=>s+p.getIndices().getCount()/3,0);assert(tris<3000);quilts.push({name,triangles:tris,bounds:b})}
 else if(/^树木_/.test(name)&&['实物贴图窗外树_0','实物贴图窗外树_1'].includes(n.getParentNode()?.getName())){for(const side of ['min','max'])for(let i=0;i<3;i++)assert(Math.abs(b[side][i]-a[side][i]-[1.8,.9,0][i])<.00001);trees.push(name)}

 else if(['主卫内部压纹隔断','主卫内部压纹隔断竖框.001'].includes(name)){assert(b.max[0]<8.74&&b.min[2]>2.04);assert(n.getExtras()['interaction_bath-partition']);}
 else if(name==='主卫内部压纹隔断固定扇'){assert(b.max[0]<8.718&&b.min[0]>8.007);assert(!n.getExtras()['interaction_bath-partition']);}
 else if(repair.geometry.includes(name)){for(const side of ['min','max'])for(let i=0;i<3;i++)assert(Math.abs(b[side][i]-a[side][i])<.0001,'Rounded surface bounds drift: '+name)}
 else{for(const side of ['min','max'])for(let i=0;i<3;i++)assert(Math.abs(b[side][i]-a[side][i])<.000001,'Unrelated drift: '+name);unrelated++}
 for(const p of n.getMesh().listPrimitives())if([95,96,97].includes(p.getMaterial().getExtras().source_material_id))assert(!p.getMaterial().getOcclusionTexture(),'Obsolete sofa AO returned');
}
for(const name of repair.removed)assert(!after.getRoot().listNodes().find(n=>n.getName()===name)?.getMesh());assert.equal(quilts.length,2);assert.equal(trees.length,6);const validation=await validator.validateBytes(new Uint8Array(await fs.readFile(process.argv[3])));assert.equal(validation.issues.numErrors,0);const report={meshes,triangles,unrelatedBoundsUnchanged:unrelated,quilts,removed:repair.removed,treeWorldOffset:[1.8,.9,0],treePartsMoved:trees.length,obsoleteSofaOcclusionRemoved:true,gltfErrors:validation.issues.numErrors};await fs.writeFile('review/comfort-geometry.json',JSON.stringify(report,null,2)+'\n');console.log({meshes,triangles,unrelated,quilts:quilts.length,trees:trees.length,gltfErrors:validation.issues.numErrors});
